apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: c1
  region: us-east-1
  version: "1.19"
managedNodeGroups:
- name: primary
  instanceType: t2.small
  minSize: 2
  maxSize: 6
  spot: true
